name: Unit tests, linting, and formatting
on: [push]
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update Rust
        run: |
          rustup override set stable
          rustup update stable
      - name: Run tests
        run: (cd back_end && cargo test)
      - name: Lint
        run: (cd back_end && cargo clippy)
      - name: Check formatting
        run: (cd back_end && cargo fmt --check)
